name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ./builder.py .
    - uses: docker/login-action@v2.1.0
      name: login to docker hub
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Push the images to docker hub
      run: |
        docker push hmx098/auth:latest
        docker push hmx098/gateway:latest
        docker push hmx098/converter_svc:latest
        docker push hmx098/notification:latest
        
